# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-6558cc591df84ab4adeda0ed3668b263
      model-name: deepseek-chat
      max-tokens: 5000
      log-requests: true
      log-responses: true
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-6558cc591df84ab4adeda0ed3668b263
      model-name: deepseek-chat
      max-tokens: 5000
      log-requests: true
      log-responses: true
